### ISSUE TITLE
How to use with Stepper Motor

### ISSUE THREAD

**Issue by HauptmannEck** [simonmonk/PhoBot#2]
I have been trying all sorts of code snippets based of your Phobot Library, the Audrino Stepper Library, and the RaspiRobot, But no matter what I try I cannot get the stepper to turn. 

Do you know what I can do to get basic forward and backward turning of a stepper using the Phobot?

**Comment by simonmonk** [comment]
Strangely enough, I have 'using a stepper with the PhoBot' near the top of my todo list. I haven't tried it, but I am hoping to give it a go tomorrow and then do a short write-up.

I'll let you know how it goes.

Si.

On 24 Sep 2015, at 04:03, HauptmannEck notifications@github.com wrote:

> I have been trying all sorts of code snippets based of your Phobot Library, the Audrino Stepper Library, and the RaspiRobot, But no matter what I try I cannot get the stepper to turn.
> 
> Do you know what I can do to get basic forward and backward turning of a stepper using the Phobot?
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Simon Monk. http://www.simonmonk.org

**Comment by simonmonk** [comment]
Hi,

There you go:

http://www.doctormonk.com/2015/09/the-phobot-board-and-servo-motors.html

Si.

On 24 Sep 2015, at 04:03, HauptmannEck notifications@github.com wrote:

> I have been trying all sorts of code snippets based of your Phobot Library, the Audrino Stepper Library, and the RaspiRobot, But no matter what I try I cannot get the stepper to turn.
> 
> Do you know what I can do to get basic forward and backward turning of a stepper using the Phobot?
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Simon Monk. http://www.simonmonk.org

**Comment by HauptmannEck** [comment]
AWESOME!

That works great. Thanks for the help.
