### ISSUE TITLE
Quetion about M1/M2 combo usage

### ISSUE THREAD

**Issue by HauptmannEck** [simonmonk/PhoBot#3]
I am just curious to get your thought on an idea I have.

I am using M3/M4 on the Phobot to run a stepper motor, but I also need to run a DC motor with both directions. Could I use the M1/M2 ports wired opposite to run the DC motor.

So M1 + would connect to the Motors + and M2's -, and M1's - would connect to the Motors - and M2's +.

Running it would be something like:
M1-50;
M1-S;
M2-50;
M2-S;

**Comment by simonmonk** [comment]
I see what you are aiming for, but if you take a look at the schematic for the PhoBot, you will see that the M1 and M2 outputs are not complementary outputs, the can only switch to GND.

Si.

On 11 Oct 2015, at 18:27, HauptmannEck notifications@github.com wrote:

> I am just curious to get your thought on an idea I have.
> 
> I am using M3/M4 on the Phobot to run a stepper motor, but I also need to run a DC motor with both directions. Could I use the M1/M2 ports wired opposite to run the DC motor.
> 
> So M1 + would connect to the Motors + and M2's -, and M1's - would connect to the Motors - and M2's +.
> 
> Running it would be something like:
> M1-50;
> M1-S;
> M2-50;
> M2-S;
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Simon Monk. http://www.simonmonk.org

**Comment by HauptmannEck** [comment]
Shame, I hoped. Oh well.
Thanks for the help
